<?php
/**
 * @var $block  MaxMage\InternationalTelephoneInput\Block\PhoneNumber
 */
?>
<script type="application/javascript">
    require([
        'jquery',
        'intlTelInput'
    ], function ($) {
        maxMageTelephoneRenderComplete = function() {
            let input = document.querySelector("input[name='telephone']");
            window.intlTelInput(input, <?php echo $block->phoneConfig(); ?>);
        }
    });
</script>