<?php
/**
 * @var $block  MaxMage\InternationalTelephoneInput\Block\PhoneNumber
 */
?>
<script type="application/javascript">
    require([
        'jquery',
        'intlTelInput'
    ], function ($) {
        maxMageTelephoneRenderComplete = function() {
            let input = document.querySelector("<?= $block->getInputSelector() ?>");
            window.intlTelInput(input, <?= $block->getJsConfig() ?>);
        }
    });
</script>